apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfsdata
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /dispatch/charts/haclst/pgha/data
    server: fsf-seo0101a-fz.adn.networklayer.com:/IBM02SV1570767_1/data01
