apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfsdataclaim
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  storageClassName: ""
